// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEfQsAOM6kJ9F-vY3OsrUzXKnofTTh4rM',
    appId: '1:743157837542:web:ef3b8bdfaf37d565add527',
    messagingSenderId: '743157837542',
    projectId: 'civicconnect-a625f',
    authDomain: 'civicconnect-a625f.firebaseapp.com',
    storageBucket: 'civicconnect-a625f.firebasestorage.app',
    measurementId: 'G-TKVHPEB3NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDExRIq8UXrToIw2owCbo3jVRLZWd-AjwQ',
    appId: '1:743157837542:android:1e71d3d1df829c49add527',
    messagingSenderId: '743157837542',
    projectId: 'civicconnect-a625f',
    storageBucket: 'civicconnect-a625f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfUFUATnPMnKuOJKrHXUvCN-myPELRHoc',
    appId: '1:743157837542:ios:61816922ba45cafeadd527',
    messagingSenderId: '743157837542',
    projectId: 'civicconnect-a625f',
    storageBucket: 'civicconnect-a625f.firebasestorage.app',
    iosBundleId: 'com.example.civicconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfUFUATnPMnKuOJKrHXUvCN-myPELRHoc',
    appId: '1:743157837542:ios:61816922ba45cafeadd527',
    messagingSenderId: '743157837542',
    projectId: 'civicconnect-a625f',
    storageBucket: 'civicconnect-a625f.firebasestorage.app',
    iosBundleId: 'com.example.civicconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEfQsAOM6kJ9F-vY3OsrUzXKnofTTh4rM',
    appId: '1:743157837542:web:0d27f015158d3608add527',
    messagingSenderId: '743157837542',
    projectId: 'civicconnect-a625f',
    authDomain: 'civicconnect-a625f.firebaseapp.com',
    storageBucket: 'civicconnect-a625f.firebasestorage.app',
    measurementId: 'G-0QTRD88YJT',
  );
}
